# Generated by Django 5.1.7 on 2025-03-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(
                default="meal_images/default_meal.jpg", upload_to="meal_images"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="available",
            field=models.BooleanField(
                default=False, verbose_name="Online Availability"
            ),
        ),
    ]
