# Generated by Django 5.1.7 on 2025-03-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_meal_image_alter_meal_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="Stock Count"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(
                default="meal_images/food1.jpg", upload_to="meal_images"
            ),
        ),
    ]
