# Generated by Django 5.1.7 on 2025-03-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_foodbag"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
